Repository nanodbc/nanodbc, pull requests merged in 2020-07, with the labels that each got.

#237 Add implementation of SQLDataSources
  .appveyor.yml
  .travis.yml
  nanodbc/nanodbc.cpp
  nanodbc/nanodbc.h
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
  test/vertica_test.cpp
  utility/ci/travis/before_script.mysql.sh
  utility/ci/travis/before_script.postgresql.sh
  utility/ci/travis/before_script.sqlite.sh
  utility/ci/travis/before_script.vertica.sh
Labels: category/feature

#238 auto_bind: Handle SQL_SS_XML
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
Labels: category/feature

#243 Install path for cmake are wrong on linux/unix
  CMakeLists.txt
Labels: category/bug

#236 Optional binding to support out-of-order retrival of unbound columns with SQLGetData
  nanodbc/nanodbc.cpp
  nanodbc/nanodbc.h
  test/mssql_test.cpp
Labels: category/enhancement
