Repository nanodbc/nanodbc, pull requests merged in 2022-04, with the labels that each got.

#295 fix: Do not restrict number of digits for SQL_C_DOUBLE
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
Labels: category/bug

#298 fix: SQLSTATE truncation (#267)
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/odbc_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
  test/vertica_test.cpp
Labels: category/bug

#259 Support table-valued parameter
  CMakeLists.txt
  example/CMakeLists.txt
  example/table_valued_parameter.cpp
  nanodbc/nanodbc.cpp
  nanodbc/nanodbc.h
  test/base_test_fixture.h
  test/mssql_test.cpp
Labels: category/feature

#301 Remove non-ascii character from source
  test/test_case_fixture.h
Labels: category/annoyance

#304 Remove unreferenced formal variable
  nanodbc/nanodbc.cpp
Labels: category/annoyance

#308 test: Fix test_error with correct SQL State and native code
  test/test_case_fixture.h
Labels: category/bug

#307 refactor: Add bind_column and unbind_column to result_impl
  nanodbc/nanodbc.cpp
Labels: category/enhancement, category/refactoring

#311 ci: Consolidate lint-*.yml into single lint.yml
  .editorconfig
  .github/workflows/lint-clang-format.yml
  .github/workflows/lint-docker.yml
  .github/workflows/lint-documentation.yml
  .github/workflows/lint-markdown.yml
  .github/workflows/lint.yml
  Dockerfile
Labels: category/chore

#312 ci: Split lint workflow into separate jobs
  .github/workflows/lint.yml
Labels: category/chore

#313 ci: Add documentation workflow for GHA
  .github/workflows/documentation.yml
  doc/requirements.txt
Labels: category/chore, category/documentation

#318 ci: Remove Circle CI configuration
  .circleci/config.yml
  README.md
Labels: category/chore

#299 Added support for binding std::string_view in table_valued_parameter.bind_strings()
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
Labels: category/enhancement

#320 chore: Rename NANODBC_H to NANODBC_NANODBC_H
  nanodbc/nanodbc.h
Labels: category/chore

#322 fix: Underflow pos in condition of result::at_end test
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/odbc_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
  test/vertica_test.cpp
Labels: category/bug

#323 fix: Null fallback was ignored for bound columns retrieved as unbound
  nanodbc/nanodbc.cpp
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/odbc_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
  test/vertica_test.cpp
Labels: category/bug
