Repository nanodbc/nanodbc, pull requests merged in 2023-08, with the labels that each got.

#389 ci: Update GitHub Actions workflows after removal of Ubuntu 18.04
  .github/workflows/ci-linux.yml
  .github/workflows/ci-windows.yml
  .github/workflows/lint.yml
Labels: category/chore

#390 ci(windows): Test MySQL using MySQL Connector 8.1
  .github/workflows/ci-windows.yml
  test/base_test_fixture.h
  test/test_case_fixture.h
Labels: category/chore

#209 Comment on data type identifier for DECIMAL
  test/test_case_fixture.h
Labels: category/annoyance, status/need-feedback

#345 C++17 type std::optional support
  CHANGELOG.md
  VERSION.txt
  nanodbc/nanodbc.cpp
  nanodbc/nanodbc.h
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
Labels: category/feature

#339 feat: Add _variant_t-based row-cached result class wrapper
  CMakeLists.txt
  nanodbc/nanodbc.h
  nanodbc/variant_row_cached_result.cpp
  nanodbc/variant_row_cached_result.h
  test/mssql_test.cpp
  test/mysql_test.cpp
  test/postgresql_test.cpp
  test/sqlite_test.cpp
  test/test_case_fixture.h
Labels: category/feature, toolset/msvc
